### ISSUE TITLE
DrugCell: hardcoded path in preprocess.sh

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DrugCell#23]
/usr/local/DrugCell/preprocess.sh: line 56: /homes/ac.rgnanaolivu/miniconda3/etc/profile.d/conda.sh: No such file or directory

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Comment by wilke** [comment]
Please don't use conda in your shell scripts. Refer to the template scripts.

**Comment by rohandavidg** [comment]
this issue has been fixed
