### ISSUE TITLE
Warning: SpearmanRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DrugCell#38]
We might want to fix that:

INFO:DrugCell:   **** TEST ****   Epoch [1/1], loss: 0.83281. This took 39.4 secs.
/opt/conda/lib/python3.7/site-packages/scipy/stats/stats.py:4484: SpearmanRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(SpearmanRConstantInputWarning())
nan
Best performed model (epoch)    0
{'test_loss': 0.0008328101038932801, 'test_pcc': -2.8085122494303505e-07, 'test_MSE': 0.8901301622390747, 'test_r2': -19.574140548706055, 'test_scc': nan, 'IMPROVE RESULT': 0.8901301622390747}

IMPROVE_RESULT MSE:     0.8901301622390747

**Comment by rohandavidg** [comment]
Just fixed this issue
INFO:CandleCkpt:Callback initialized.
Checkpoint save interval == 0 -> checkpoints are disabled.
INFO:CandleCkpt:Checkpoint save interval == 0 -> checkpoints are disabled.
INFO:DrugCell:== Epoch [0/200] ==
INFO:DrugCell:   **** TRAINING ****   Epoch [1/200], loss: 31.50916. This took 35.8 secs.
INFO:DrugCell:   **** TEST ****   Epoch [1/200], loss: 0.86188. This took 41.4 secs.
nan
INFO:DrugCell:== Epoch [1/200] ==
INFO:DrugCell:   **** TRAINING ****   Epoch [2/200], loss: 31.43307. This took 32.4 secs.
INFO:DrugCell:   **** TEST ****   Epoch [2/200], loss: 0.85998. This took 37.8 secs.
nan
INFO:DrugCell:== Epoch [2/200] ==
INFO:DrugCell:   **** TRAINING ****   Epoch [3/200], loss: 31.35702. This took 33.5 secs.
INFO:DrugCell:   **** TEST ****   Epoch [3/200], loss: 0.85807. This took 39.1 secs.
nan
INFO:DrugCell:== Epoch [3/200] ==
INFO:DrugCell:   **** TRAINING ****   Epoch [4/200], loss: 31.28103. This took 33.7 secs.
INFO:DrugCell:   **** TEST ****   Epoch [4/200], loss: 0.85616. This took 39.3 secs.
0.6228883221333422

**Comment by rohandavidg** [comment]
fixed this issue with the latest pull request
