### ISSUE TITLE
Use of absolute paths and user specific configuration and directories 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DrugCell#8]
https://github.com/JDACS4C-IMPROVE/DrugCell/blob/b26e0f6e414b46c7773b0195c0dc47618cb8916b/train.sh#L70

Please avoid any absolute paths in your scripts. Provide a setup script if necessary. This will not work for any other user.

**Comment by rohandavidg** [comment]
i have updated the code. Thank you for pointing it out.
